#
# Travis CI configuration file for MMD.
#

language: c

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "hHw4xKUA436afMrkTmUBMCewuq9E40o3PvsU6q5mDARf0B6NCFymKTkQtLGwqHkimOGwHufHwGAQWsgyAuPe43d9366Uun/v1kNS1HAYf2/rj07fzVuXM21sx5hcLXlcBpzrXDekzrI2bIiCYDg+ELSI8KZqDSwi4r6+/ri1YiQJ2SNWgG9TRhSid3BN9Q0l86VlAu6ErLuru8hqXnHYGw5Bv8DFgolL+TjZUbSWC7bdvx4DiX/hSyStW+vpyf9yvgB2wkcgzBLA+0NOoV7YOP5b/rXyTBsS7iC03V3A4p7uj+oAl5MQBulaxDFP3ofscu0s3AOx7x+lips6zXZ4qGVbrix7yalsMqJwnw2pElr7sE9K0AVYbNI9PKa8MK5kF4hAQ34hN0BsLNMUx9ZC3SPRX5b5tNiIlyTDH8Gk7GVIbQZ2rbhxobkCDz+FeYfmaCUwXgtRVtlUW5/ENX7DlneMttrodSX7hJrTqphoP4sS9siEiOLuv9uhI51klkiLd2JqKRRgALPvE19Hu1IeTeNWLCHp1WRbVX5D4BLD+mdn0gRJiKL8wEH7nrla5wxhI7CrzHQ039fejkTRFuY32iH+315MSIpSrqvljeRbv3BjHQ/t+z+dqfqXE/trZUQplKTCm7OW8G8jfBj9gv12Tx4/DlAKVLwasCsQ3XVgAn8="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

jobs:
  include:
    # Linux-specific build stuff
    - os: linux
      dist: focal
      virt: vm
      env:
        - ASAN_OPTIONS=leak_check_at_exit=false
      script: make sanitizer && make test && make cppcheck
      addons:
        apt:
          packages: [cppcheck]
        coverity_scan:
          project:
            name: "michaelrsweet/mmd"
            description: "Miniature Markdown 'Library' and Utility"
          notification_email: michael.r.sweet@gmail.com
          build_command_prepend: "make clean"
          build_command: "make"
          branch_pattern: master

    # macOS-specific build stuff
    - os: osx
      osx_image: xcode12.2
      script: make sanitizer && make test

notifications:
  email:
    recipients:
      - msweet@msweet.org
